version: '3'

services:

    db:
        image: postgres
        container_name: "postgres_container"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: chatbot 
        volumes:
            - ./init.db.sql:/docker-entrypoint-initdb.d/init.db.sql
        ports:
            - 5432:5432

    worker:
        build: ./worker
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
            - SENDGRID_FROM_EMAIL=XXXINPUT-SENDFROM-EMAIL-HEREXXXX
            - SENDGRID_API_KEY=XXXINPUT-KEY-HEREXXX
            - CELERY_RESULT_BACKEND=db+postgresql://postgres:postgres@db:5432/chatbot
        volumes:
            - ./worker/worker.py:/app/worker.py

    redis:
        image: redis
        ports:
            - "6379:6379"  

    chatbot_parser:
        build: ./chatbot_parser
        container_name: "chatbot_parser"
        ports: 
          - 5050:5050
        depends_on:
            - db

    shrug_command:
        build: ./shrug_command
        container_name: "shrug_command"
        ports: 
          - 5051:5051
        depends_on:
            - db
    
    email_command:
        build: ./email_command
        volumes:
            - ./worker/worker.py:/app/worker.py
        container_name: "email_command"
        image: email-service-image
        ports:
            - 5052:5052
        environment:
           - SENDGRID_FROM_EMAIL=XXXINPUT-FROM-EMAIL-HEREXXX
           - SENDGRID_API_KEY=XXXINPUT-KEY-HEREXXX
           - CELERY_BROKER_URL=redis://redis:6379/0
           - CELERY_RESULT_BACKEND=db+postgresql://postgres:postgres@db:5432/chatbot
        depends_on:
            - db
            - redis
            - worker
    
    job_viewer:
        image: mher/flower
        environment:
            - CELERY_BROKER_URL=redis://redis:6379
            - FLOWER_PORT=8888
        ports:
            - 8888:8888
        depends_on:
            - redis
        
    