version: "3.7"

services:
  db:
      image: postgres:latest
      container_name: db
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: app_db
      volumes:
        - postgres-volume:/var/lib/postgresql/data
        - ./init.db.sql:/docker-entrypoint-initdb.d/init.db.sql
      ports:
        - "5432:5432"

  user_app:
    build: ./user
    container_name: user_app
    environment:
      SENDGRID_FROM_EMAIL: ***
      SENDGRID_API_KEY: ***
      SECRET_KEY: ***
      FINANCE_APP: http://localhost:5051
      POKEMON_APP: http://localhost:5052
      NEWS_APP: http://localhost:5053
      STREETVIEW_APP: http://localhost:5054
      WEATHER_APP: http://localhost:5055
    volumes:
      - flask-session:/app/flask_session
    ports:
      - "5050:5050"
  
  finance_app:
    build: ./finance
    container_name: finance_app
    environment:
      NASDAQ_DATA_LINK_API_KEY: ***
      SECRET_KEY: ***
      USER_APP: http://localhost:5050
    volumes:
      - flask-session:/app/flask_session
    ports:
      - "5051:5051"
  
  pokemon_app:
    build: ./pokemon
    container_name: pokemon_app
    environment:
      SECRET_KEY: ***
      USER_APP: http://localhost:5050
    volumes:
      - flask-session:/app/flask_session
    ports:
      - "5052:5052"
  
  news_app:
    build: ./news
    container_name: news_app
    environment:
      NEWS_API_KEY: ***
      SECRET_KEY: ***
      USER_APP: http://localhost:5050
    volumes:
      - flask-session:/app/flask_session
    ports:
      - "5053:5053"
  
  streetview_app:
    build: ./streetview
    container_name: streetview_app
    environment:
      STREETVIEW_API_KEY: ***
      SECRET_KEY: ***
      USER_APP: http://localhost:5050
    volumes:
      - flask-session:/app/flask_session
    ports:
      - "5054:5054"
  
  weather_app:
    build: ./weather
    container_name: weather_app
    environment:
      WEATHER_API_KEY: ***
      SECRET_KEY: ***
      USER_APP: http://localhost:5050
    volumes:
      - flask-session:/app/flask_session
    ports:
      - "5055:5055"

volumes:
  postgres-volume: {}
  flask-session: {}
